name: ExpiCheck Push Notification

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  send-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Send ExpiCheck reminders
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node push-notifications.js
